# The URL the site will be built for
base_url = "https://www.xuanruiqi.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Xuanrui Qi"
description = "PhD candidate in mathematics, Nagoya University"

taxonomies = [
    { name = "tags", feed = true },
]

[markdown.highlighting]
error_on_missing_language = false
style = "inline"
theme = "solarized-light"

[extra]
# Put all your custom variables here
